/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestePratico;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class AgendaPanel extends javax.swing.JPanel {

    public static void main(String[] args) {

    }
    ArrayList<Contato> ListaCon;
    String modo;

    public void LoadTableCon() {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"idcontato", "Nome", "sobrenome", "telefone1", "telefone2"}, 0);
        for (int i = 0; i < ListaCon.size(); i++) {
            modelo.addRow(new Object[]{ListaCon.get(i).getIdcontato(), ListaCon.get(i).getNomeContato(), ListaCon.get(i).getSobrenome(), ListaCon.get(i).getTelefone1(), ListaCon.get(i).getTelefone2()});
        }
        tbl_con_cons.setModel(modelo);
    }

    /**
     * Creates new form AgendaPanel
     */
    public AgendaPanel() {
        initComponents();
        setLocationRelativeTo(null);
        ListaCon = new ArrayList();
        modo = "navegar";
        Interface();

    }

    public void Interface() {
        switch (modo) {
            case "navegar":
                btn_con_salvar.setEnabled(false);
                btn_con_cancelar.setEnabled(false);
                c_con_idcontato.setEnabled(false);
                c_con_nome.setEnabled(false);
                c_con_sobrenome.setEnabled(false);
                c_con_telefone1.setEnabled(false);
                c_con_telefone2.setEnabled(false);
                btn_con_novo.setEnabled(true);
                btn_con_editar.setEnabled(false);
                btn_con_excluir.setEnabled(false);
                break;

            case "novo":
                btn_con_salvar.setEnabled(true);
                btn_con_cancelar.setEnabled(true);
                c_con_idcontato.setEnabled(true);
                c_con_nome.setEnabled(true);
                c_con_sobrenome.setEnabled(true);
                c_con_telefone1.setEnabled(true);
                c_con_telefone2.setEnabled(true);
                btn_con_novo.setEnabled(false);
                btn_con_editar.setEnabled(false);
                btn_con_excluir.setEnabled(false);

                break;

            case "Editar":
                btn_con_salvar.setEnabled(true);
                btn_con_cancelar.setEnabled(true);
                c_con_idcontato.setEnabled(true);
                c_con_nome.setEnabled(true);
                c_con_sobrenome.setEnabled(true);
                c_con_telefone1.setEnabled(true);
                c_con_telefone2.setEnabled(true);
                btn_con_novo.setEnabled(false);
                btn_con_editar.setEnabled(false);
                btn_con_excluir.setEnabled(false);

                break;

            case "Excluir":

                btn_con_salvar.setEnabled(false);
                btn_con_cancelar.setEnabled(false);
                c_con_idcontato.setEnabled(false);
                c_con_nome.setEnabled(false);
                c_con_sobrenome.setEnabled(false);
                c_con_telefone1.setEnabled(false);
                c_con_telefone2.setEnabled(false);
                btn_con_novo.setEnabled(true);
                btn_con_editar.setEnabled(false);
                btn_con_excluir.setEnabled(false);

                break;

            case "click":

                btn_con_salvar.setEnabled(false);
                btn_con_cancelar.setEnabled(false);
                c_con_idcontato.setEnabled(false);
                c_con_nome.setEnabled(false);
                c_con_sobrenome.setEnabled(false);
                c_con_telefone1.setEnabled(false);
                c_con_telefone2.setEnabled(false);
                btn_con_novo.setEnabled(true);
                btn_con_editar.setEnabled(true);
                btn_con_excluir.setEnabled(true);

                break;
            default:
                System.out.println("Modo invalido");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_con_cons = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        c_con_idcontato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_con_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_con_sobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_con_telefone1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_con_telefone2 = new javax.swing.JTextField();
        btn_con_salvar = new javax.swing.JButton();
        btn_con_cancelar = new javax.swing.JButton();
        btn_con_novo = new javax.swing.JButton();
        btn_con_editar = new javax.swing.JButton();
        btn_con_excluir = new javax.swing.JButton();

        tbl_con_cons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Sobrenome", "Telefone 1", "Telefone 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_con_cons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_con_consMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_con_cons);
        if (tbl_con_cons.getColumnModel().getColumnCount() > 0) {
            tbl_con_cons.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Contatos", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Contato"));

        jLabel1.setText("Id:");

        c_con_idcontato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_con_idcontatoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Telefone 1:");

        jLabel5.setText("Telefone 2:");

        btn_con_salvar.setText("Salvar");
        btn_con_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_con_salvarActionPerformed(evt);
            }
        });

        btn_con_cancelar.setText("Cancelar");
        btn_con_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_con_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c_con_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_con_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_con_idcontato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btn_con_salvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_con_cancelar)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c_con_telefone2))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(c_con_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(c_con_idcontato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(c_con_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(c_con_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(c_con_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(c_con_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_con_salvar)
                    .addComponent(btn_con_cancelar))
                .addContainerGap())
        );

        btn_con_novo.setText("Novo");
        btn_con_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_con_novoActionPerformed(evt);
            }
        });

        btn_con_editar.setText("Editar");
        btn_con_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_con_editarActionPerformed(evt);
            }
        });

        btn_con_excluir.setText("Excluir");
        btn_con_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_con_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btn_con_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_con_editar)
                .addGap(100, 100, 100)
                .addComponent(btn_con_excluir)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_con_novo)
                    .addComponent(btn_con_editar)
                    .addComponent(btn_con_excluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void c_con_idcontatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_con_idcontatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_con_idcontatoActionPerformed

    private void btn_con_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_con_salvarActionPerformed
        if (modo.equals("novo")) {
            int id = Integer.parseInt(c_con_idcontato.getText());
            Contato C = new Contato(id, c_con_nome.getText(), c_con_sobrenome.getText(), c_con_telefone1.getText(), c_con_telefone2.getText());
            ListaCon.add(C);
        } else if (modo.equals("editar")) {
            int index = tbl_con_cons.getSelectedRow();
            ListaCon.get(index).setIdcontato(index);
            ListaCon.get(index).setNomeContato(c_con_nome.getText());
            ListaCon.get(index).setNomeContato(c_con_sobrenome.getText());
            ListaCon.get(index).setNomeContato(c_con_telefone1.getText());
            ListaCon.get(index).setNomeContato(c_con_telefone2.getText());
        }

        LoadTableCon();

        modo = "navegar";
        Interface();
        c_con_idcontato.setText("");
        c_con_nome.setText("");
        c_con_sobrenome.setText("");
        c_con_telefone1.setText("");
        c_con_telefone2.setText("");
    }//GEN-LAST:event_btn_con_salvarActionPerformed

    private void btn_con_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_con_novoActionPerformed
        c_con_idcontato.setText("");
        c_con_nome.setText("");
        c_con_sobrenome.setText("");
        c_con_telefone1.setText("");
        c_con_telefone2.setText("");

        modo = "novo";
        Interface();
    }//GEN-LAST:event_btn_con_novoActionPerformed

    private void btn_con_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_con_cancelarActionPerformed
        c_con_idcontato.setText("");
        c_con_nome.setText("");
        c_con_sobrenome.setText("");
        c_con_telefone1.setText("");
        c_con_telefone2.setText("");

        modo = "navegar";
        Interface();
    }//GEN-LAST:event_btn_con_cancelarActionPerformed

    private void tbl_con_consMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_con_consMouseClicked
        int index = tbl_con_cons.getSelectedRow();
        if (index >= 0 && index < ListaCon.size());
        Contato C = ListaCon.get(index);
        c_con_idcontato.setText(String.valueOf(C.getIdcontato()));
        c_con_nome.setText(C.getNomeContato());
        c_con_sobrenome.setText(C.getSobrenome());
        c_con_telefone1.setText(C.getTelefone1());
        c_con_telefone2.setText(C.getTelefone2());

        modo = "click";
        Interface();
    }//GEN-LAST:event_tbl_con_consMouseClicked

    private void btn_con_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_con_editarActionPerformed
        modo = "editar";
        Interface();
    }//GEN-LAST:event_btn_con_editarActionPerformed

    private void btn_con_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_con_excluirActionPerformed
        int index = tbl_con_cons.getSelectedRow();
        if (index >= 0 && index < ListaCon.size());
        Contato C = ListaCon.get(index);
        ListaCon.remove(index);

        LoadTableCon();

        modo = "navegar";
        Interface();
    }//GEN-LAST:event_btn_con_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_con_cancelar;
    private javax.swing.JButton btn_con_editar;
    private javax.swing.JButton btn_con_excluir;
    private javax.swing.JButton btn_con_novo;
    private javax.swing.JButton btn_con_salvar;
    private javax.swing.JTextField c_con_idcontato;
    private javax.swing.JTextField c_con_nome;
    private javax.swing.JTextField c_con_sobrenome;
    private javax.swing.JTextField c_con_telefone1;
    private javax.swing.JTextField c_con_telefone2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_con_cons;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
